sudo: false

language: go

go:
  - 1.8

addons:
  apt:
    packages:
      - socklog
      - runit

cache:
  apt: true
  directories:
    - /home/travis/perl5
    - /home/travis/gopath/bin
    - /home/travis/gopath/pkg
    - /home/travis/gopath/src/github.com/axw
    - /home/travis/gopath/src/github.com/mattn
    - /home/travis/gopath/src/github.com/pborman
    - /home/travis/gopath/src/golang.org
    - /home/travis/gopath/src/gopkg.in

before_install:
  - export PATH="$HOME/perl5/bin:$PATH"
  - curl -L https://cpanmin.us | perl - App::cpanminus
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm -nq CPAN::Meta
  - cpanm -nq File::Spec
  - cpanm -nq Narada
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - go get -v golang.org/x/tools/cmd/cover
script:
  - RELEASE_TESTING=1 ./release
  - mkdir _live/ && ln -s ../.release _live/.release && cd _live/
  - narada-install "$(cat ../VERSION)" </dev/null
  - narada-start-services & sleep 1
  - prove -r
